- app/views/layouts/application.html.erb
> Ooyaryouhei

- app/views/layouts/application.html.erb
> Saki.ojima

- app/assets/stylesheets/public/shipping_addresses.scss
- app/controllers/public/shipping_addresses_controller.rb
- app/helpers/public/shipping_addresses_helper.rb
- app/models/shipping_address.rb
- config/routes.rb
- db/migrate/20221018024839_create_shipping_addresses.rb
- db/schema.rb
- test/controllers/public/shipping_addresses_controller_test.rb
- test/fixtures/shipping_addresses.yml
- test/models/shipping_address_test.rb
shipping_addressのモデルとコントローラを追加し、ルーティングを記述しました
> Make shipping address

- app/assets/stylesheets/admin/orders.scss
- app/controllers/admin/orders_controller.rb
- app/helpers/admin/orders_helper.rb
- app/models/order.rb
- config/routes.rb
- db/migrate/20221018023909_create_orders.rb
- db/schema.rb
- test/controllers/admin/orders_controller_test.rb
- test/fixtures/orders.yml
- test/models/order_test.rb
> order-model作成

- app/assets/stylesheets/admin/items.scss
- app/assets/stylesheets/public/items.scss
- app/controllers/admin/items_controller.rb
- app/controllers/public/items_controller.rb
- app/helpers/admin/items_helper.rb
- app/helpers/public/items_helper.rb
- app/models/item.rb
- config/routes.rb
- db/migrate/20221018044954_create_items.rb
- db/schema.rb
- test/controllers/admin/items_controller_test.rb
- test/controllers/public/items_controller_test.rb
- test/fixtures/items.yml
- test/models/item_test.rb
itemsのコントローラとモデルを作成し、ルーティングを記述しました
> Make items

- app/assets/stylesheets/public/cart_items.scss
- app/controllers/public/cart_items_controller.rb
- app/helpers/public/cart_items_helper.rb
- app/models/cart_item.rb
- config/routes.rb
- db/migrate/20221018044812_create_cart_items.rb
- db/schema.rb
- test/controllers/public/cart_items_controller_test.rb
- test/fixtures/cart_items.yml
- test/models/cart_item_test.rb
cart-itemsのモデル、コントローラー、ルーティングを追加しました。
> Cart items

- app/models/cart_item.rb
- app/models/customer.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_item.rb
> association

- app/controllers/admin/genres_controller.rb
- app/javascript/packs/application.js
- app/models/genre.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/layouts/application.html.erb
> [add]genres

- app/controllers/public/items_controller.rb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
> Make public items

- app/controllers/public/customers_controller.rb
- app/controllers/public/registrations_controller.rb
- app/controllers/public/sessions_controller.rb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/unsubscribe.html.erb
- config/routes.rb
- db/schema.rb
*顧客が退会できる機能を追加しました。
*再登録するとき同じメールアドレス？での新規登録ができないのを確認してます
↑そもそも退会できてなさそうでした。。
> [add] 退会機能実装

- app/controllers/admin/items_controller.rb
- app/controllers/public/items_controller.rb
- app/controllers/public/shipping_addresses_controller.rb
- app/models/shipping_address.rb
- app/views/layouts/_errors.html.erb
- app/views/public/shipping_addresses/_address_form.html.erb
- app/views/public/shipping_addresses/_index.html.erb
- app/views/public/shipping_addresses/create.js.erb
- app/views/public/shipping_addresses/destroy.js.erb
- app/views/public/shipping_addresses/edit.html.erb
- app/views/public/shipping_addresses/error.js.erb
- app/views/public/shipping_addresses/index.html.erb
- config/routes.rb
* コントローラとview（index,edit）を実装しました
* 販売ステータスが売切れになっている商品のshowページにアクセスできないよう、コントローラに記述を追加しました
> 【追加】shipping addresses index/edit 他

- config/routes.rb
> [Update] routes修正

- config/routes.rb
> fix admin-customerspage

- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
> [Fix]kaminari_bootstrap

- app/controllers/public/customers_controller.rb
- app/controllers/public/sessions_controller.rb
- app/models/customer.rb
- app/views/admin/customers/index.html.erb
- app/views/layouts/application.html.erb
- app/views/public/customers/unsubscribe.html.erb
- app/views/public/registrations/new.html.erb
*退会機能をなおしました。
*(論理削除のメソッドなのでデータ自体は残るものらしいです..)
> [fix] unsubscribe

- app/views/layouts/application.html.erb
検索フォームをヘッダーに追加、実際の検索実装はしていません。
> [add]search form

- app/controllers/public/customers_controller.rb
- app/controllers/public/sessions_controller.rb
- app/models/customer.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/layouts/application.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/customers/unsubscribe.html.erb
- app/views/public/registrations/new.html.erb
- config/routes.rb
会員一覧画面、会員詳細画面、会員情報編集画面を作成しました。
> [Add] admin/customer-index,show,edit

- app/controllers/admin/items_controller.rb
- app/controllers/public/items_controller.rb
- app/models/item.rb
- app/views/admin/items/_items_form.html.erb
- app/views/admin/items/error.js.erb
- app/views/layouts/_errors.html.erb
- app/views/public/items/_sidebar.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- config/application.rb
- config/locales/ja.yml
- config/locales/models/ja.yml
- db/migrate/20221023144518_remove_index_from_items.rb
- db/migrate/20221023144705_remove_index_from_shipping_addresses.rb
- db/schema.rb
* items(admin)にバリデーションを追加しました
* エラーメッセージの翻訳を追加しました
* items(public)にジャンル検索機能を実装しました
* items,shipping_addressesで外部キーに貼られていたインデックスを解除しました
> [Add]items

- app/models/item.rb
* itemsのmodelファイルで、画像に関する記述を修正しました
> 【修正】items model

- app/controllers/public/orders_controller.rb
- app/views/public/orders/new.html.erb
- db/schema.rb
> [Update] public-order

- app/controllers/admin/items_controller.rb
> [Fix]items

- app/controllers/application_controller.rb
- app/views/admin/orders/show.html.erb
- app/views/public/orders/confirm.html.erb
- config/application.rb
- config/locales/ja.yml
> [Fix] test1

- app/controllers/admin/sessions_controller.rb
- app/views/public/cart_items/index.html.erb
> [fix]admin

- app/controllers/public/items_controller.rb
- app/javascript/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/public/items/_sidebar.html.erb
- app/views/public/items/index.html.erb
* 検索フォームを追加しました
* ページネーションのCSSを変更しました
> [Add] search_form
